ISchools/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path,include
from login import urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(urls)),
    path('', include('django.contrib.auth.urls')),
    path('password_reset', views.password_reset, {'template_name': 'password/password_recovery.html'}, name='password_reset'),
    path('password_reset/done/', views.password_reset_done, {'template_name': 'password/password_reset_done.html'}),
    path('reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',views.password_reset_confirm),
    path('reset/done/',views.password_reset_complete),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.urls import path
from login import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('loggedin/', views.loggedin, name='loggedin'),
    path('loggedin/(?P<pk>\d+)/following/',views.followers, name='followers'),
    path('post/',views.user_post, name='userpost'),
    path('friends/',views.friends, name='friends'),
    path('loggedin/(?P<pk>\d+)/profile/', views.profile, name='profile'),
    path('update_user/', views.update_user, name='update_user'),
    path('post/(?P<pk>\d+)/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('post/(?P<pk>\d+)/post_deatil/', views.post_details,name='post_details'),
    path('post/(?P<pk>\d+)/likes', views.add_like,name= 'add_like'),
    path('post/(?P<pk>\d+)/unlike', views.delete_like, name= 'delete_like'),
    path('friends/(?P<pk>\d+)/follow', views.follow,name='follow'),
    path('friends/(?P<pk>\d+)/unfollow', views.unfollow, name='unfollow'),
    path('profile/(?P<pk>\d+)/my_posts/', views.my_posts, name='my_posts'),
    path('profile/myposts/(?P<pk>\d+)/delete_post', views.delete_post, name='delete_post'),
]

login/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Post(models.Model):
    username = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    published_date = models.DateTimeField()

    def __str__(self):
        return f"{self.username}"


class User_details(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    date_of_birth = models.DateField()
    phone = models.BigIntegerField(blank=True)
    image = models.ImageField(upload_to='profile_image', blank=True)
    interests = models.CharField(max_length=100, default='none')


class Comments(models.Model):
    post = models.ForeignKey('Post', on_delete= models.CASCADE)
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    text = models.TextField()
    created_date = models.DateTimeField()

    def __str__(self):
        return self.text


class Likes(models.Model):
    user = models.ForeignKey('auth.User',on_delete=models.CASCADE)
    post = models.ForeignKey('Post',on_delete=models.CASCADE)
    liked_date = models.DateTimeField()

    def __str__(self):
        return f"{self.user}"


class Following(models.Model):
    user = models.ForeignKey('auth.User',on_delete=models.CASCADE)
    friend = models.ForeignKey('auth.User',on_delete=models.CASCADE,related_name='follower')

    def __str__(self):
        return f'{self.user} follows {self.friend}'

login/forms.py
from django import forms
from login.models import Post,User_details, Comments
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm ,UserChangeForm
from django.contrib.auth.models import User


class Post_form(ModelForm):
    text = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control', 'rows':'3', 'style':' box-shadow: 0 1px 2px 0 lightblue, 0 2px 10px 0 lightblue;'}))

    class Meta:
        model = Post
        fields = {'text'}


class Login(forms.Form):
    username = forms.CharField(max_length=20,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'username'}))
    password = forms.CharField(max_length=20,widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'password'}))


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'class':'form-control','placeholder':'firstname'}))
    last_name = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'class':'form-control','placeholder':'lastname'}))
    email = forms.EmailField(max_length=254,)
    username = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class':'form-control','placeholder':'username'}))
    password1 = forms.PasswordInput()
    password2 = forms.PasswordInput()

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.fields['password1'].help_text = ''
        self.fields['password2'].help_text = ''

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')


class Edit_profile(forms.Form):
    first_name = forms.CharField(max_length=30,
                                 widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'firstname'}))
    last_name = forms.CharField(max_length=30,
                                widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'lastname'}))


class CommentForm(ModelForm):
    text = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '3',
                                                        'style': ' box-shadow: 0 1px 2px 0 lightblue, 0 2px 10px 0 lightblue;'}))

    class Meta:
        model = Comments
        fields = {'text'}


class Personal_details(ModelForm):
    interests = forms.CharField(max_length=30,
                                widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'eg: c,python,c++,java'}))

    class Meta:
        model = User_details
        fields = {'phone','image','date_of_birth','interests'}
        date_of_birth = forms.DateField(
            widget=forms.DateInput(format='%m/%d/%Y'),
            input_formats=('%m/%d/%Y',)
        )
        phone = forms.RegexField(regex=r'^\d{9,15}$')

login/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect
from login.forms import Login,SignUpForm,Post_form,Edit_profile,Personal_details,CommentForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login ,logout
from login.models import Post,User_details,Likes,Following
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def home(request):
    form = Login()
    return render(request, 'home.html',{'form':form})


def user_login(request):
    if request.method == 'POST':
        form = Login(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect('/loggedin/')
            else:
                return HttpResponse("user not found.")
    else:
        form = Login()
    return render(request, 'login.html', {'form': form})


@login_required()
def my_posts(request,pk):
    user = User.objects.get(pk=pk)
    posts = user.post_set.all().order_by('-published_date')
    return render(request,'my_posts.html',{'posts':posts})


@login_required()
def delete_post(request,pk):
    post = Post.objects.get(pk=pk)
    post.delete()
    return redirect('my_posts')


@login_required()
def add_like(request, pk):
    post = Post.objects.get(pk=pk)
    user = request.user
    liked_date = timezone.now()
    l = Likes(post=post, user=user, liked_date=liked_date)
    l.save()
    return redirect('loggedin')


@login_required()
def delete_like(request, pk):
    post = Post.objects.get(pk=pk)
    like = Likes.objects.get(post=post, user=request.user)
    like.delete()
    return redirect('loggedin')


@login_required()
def post_details(request, pk):
    post = Post.objects.get(pk=pk)
    form = CommentForm()
    return render(request, 'post_details.html',{'post': post, 'form':form})


@login_required()
def add_comment_to_post(request, pk):
    post = Post.objects.get(pk=pk)
    if request.method == 'POST':
        commentform = CommentForm(request.POST)
        if commentform.is_valid():
            cobj = commentform.save(commit=False)
            cobj.post = post
            cobj.created_date = timezone.now()
            cobj.author = request.user
            cobj.save()
            return redirect('post_details', pk=post.pk)
    return redirect('post_details', pk=post.pk)


@login_required()
def user_logout(request):
    logout(request)
    return redirect('home')


@login_required()
def user_post(request):
    if request.method == 'POST':
        postform = Post_form(request.POST)
        if postform.is_valid():
            obj = postform.save(commit=False)
            obj.username = request.user
            obj.published_date = timezone.now()
            obj.save()
            return redirect('loggedin')
    return redirect('loggedin')


@login_required()
def profile(request,pk):
    user = User.objects.get(pk=pk)
    return render(request, 'profile.html', {'user': user})


@login_required()
def friends(request):
    users = User.objects.all().exclude(pk=request.user.id)
    li2 = []
    fols = Following.objects.filter(user_id=request.user.id)
    for fol in fols:
        li2.append(fol.friend.username)
    return render(request, 'friends.html', {'users':users,'followers':fols,'followlist':li2})


@login_required()
def followers(request,pk):
    user = User.objects.get(pk=pk)
    return render(request,'following.html',{'user':user})


@login_required()
def follow(request, pk):
    friend = User.objects.get(pk=pk)
    user = request.user
    f = Following(user=user, friend=friend)
    f.save()
    return redirect('friends')


@login_required()
def unfollow(request, pk):
    user1 = User.objects.get(pk=pk)
    user = User.objects.get(pk=request.user.id)
    follower = user.following_set.get(friend_id=user1.id)
    follower.delete()
    return redirect('friends')


@login_required()
def loggedin(request):
    form = Post_form
    likes = Likes.objects.filter(user_id=request.user.id)
    li = []
    for like in likes:
        li.append(like.post_id)
    user = User.objects.get(pk=request.user.id)
    post = Post.objects.filter(username__follower__user=request.user).order_by('-published_date')
    page = request.GET.get('page', 1)
    paginator = Paginator(post, 4)
    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page(1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)
    return render(request, 'loggedin.html', {'form': form, 'posts': post,'likes':li})


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return HttpResponseRedirect('/loggedin/')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})


@login_required
def update_user(request):
    if request.method == 'POST':
        form1 = Edit_profile(request.POST)
        form2 = Personal_details(request.POST, request.FILES)
        if form1.is_valid() and form2.is_valid():
            user = User.objects.get(username=request.user)
            user.first_name = form1.cleaned_data.get('first_name')
            user.last_name = form1.cleaned_data.get('last_name')
            user.save()
            if User_details.objects.filter(user=request.user).exists() :
                user = User_details.objects.get(user=request.user)
                user.date_of_birth = form2.cleaned_data.get('date_of_birth')
                user.image = form2.cleaned_data.get('image')
                user.phone = form2.cleaned_data.get('phone')
                user.interests = form2.cleaned_data.get('interests')
                user.save()
                print("success")
            else:
                print("not-success")
                user = request.user
                phone = form2.cleaned_data.get('phone')
                image = form2.cleaned_data.get('image')
                dob = form2.cleaned_data.get('date_of_birth')
                f = User_details(user=user,phone=phone,image=image,date_of_birth=dob)
                f.save()
            return redirect('profile',pk=request.user.id)
    else:
        form1 = Edit_profile()
        form2 = Personal_details()
    return render(request,'edit_profile.html',{'form1':form1, 'form2':form2})

templates/edit_profile.html
{% extends 'loggedin.html' %}
{% block container %}
    {% load bootstrap %}
    <div class="container">
      <form class="loginform" method="post" action="{% url 'update_user' %}" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form1|bootstrap }}
          {{ form2|bootstrap }}
          <button type="submit" class="btn btn-info">update</button>
       </form>
  </div>
{% endblock %}

templates/following.html
{% extends 'loggedin.html' %}
{% block container %}
  <div class="container">
   <h3 class="text-info">Followed by you : </h3><hr>
  {% for follower in user.following_set.all %}
     <div style="border: 1px solid lightblue;margin-top:5px;border-radius: 5px;padding: 5px; box-shadow: 0 1px 2px 0 lightblue, 0 2px 10px 0 lightblue;">
     <center>
     <img style="border-radius: 50%;" src="{{ follower.friend.user_details.image.url }}" alt="not uploaded" width="50px" height="50px">
     <h3 class="text-primary">{{ follower.friend.username }}</h3>
     </center>
       <table class="tabl" width="100%">
           <tr>
               <td><a href="{% url 'profile' pk=follower.friend.pk %}">profile</a></td>
               <td><a href="{% url 'unfollow' pk=follower.friend.pk %}">unfollow</a></td>
           </tr>
       </table>
     </div>
  {% endfor %}
 </div>

{% endblock %}

templates/friend_profile.html
{% extends 'profile.html' %}
{% block profile_buttons %}
{% endblock %}

templates/friends.html
{% extends 'loggedin.html' %}
{% load static %}
{% block container %}
    {% block extra-css %}
     <link rel="stylesheet" href="{% static 'followers.css' %}">
    {% endblock %}
 <div class="container">
   <h3 class="text-info">Users : </h3><hr>
  {% for user in users %}
     <div style="border: 1px solid lightblue;margin-top:5px;border-radius: 5px;padding: 5px; box-shadow: 0 1px 2px 0 lightblue, 0 2px 10px 0 lightblue;">
     <table width="100%">
           <tr>
               <td><i class="fa fa-user"></i>  {{ user.username }}</td>
               {% if user.username in followlist %}
                 <td><a href="{% url 'unfollow' pk=user.pk %}">unfollow</a></td>
               {% else %}
                   <td><a href="{% url 'follow' pk=user.pk %}">Follow</a></td>
               {% endif %}
           </tr>
       </table>
     </div>
  {% endfor %}
 </div>
{% endblock %}

templates/home.html
<!DOCTYPE html>
<html lang="en">
{% block head %}
<head>
    {% load staticfiles %}
<title>Home</title>
<link rel="icon" TYPE="image" href="{% static 'site-icon.png' %}">
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.2/css/bootstrap.min.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.1/css/all.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{% static 'style.css' %}">
 {% block extra-css %}
 {% endblock %}
<title>Title</title>
</head>
{% endblock %}
<body bgcolor="#e9ecef5e">
  {% block header %}
   <div class="jumbotron text-center text-success">
    <h1 class="display-4" style="font-family: 'Ink Free';font-weight: bold">Follow Me<sub style="font-weight: normal;font-size: small">to be a nerd</sub></h1>
    <h5 style="padding-bottom: 4px;color:mediumseagreen;">share your knowledge here</h5>
   </div>
  {% endblock %}
  {% block navbar %}
  <nav class="navbar navbar-expand-lg navbar-light">
    <a class="navbar-brand text-success" href="{% url 'home' %}" style="font-family: 'Ink Free';font-weight: bold">Follow Me</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav navbar-right">
          {% block logout %}
        <li class="nav-item"><a class="nav-link text-info" style="font-weight: bold" href="{% url 'signup' %}"><i class="fa fa-user"></i>  sign-up</a></li>
          {% endblock %}
      </ul>
    </div>
  </nav>
  {% endblock navbar %}

  {% block container %}
      <div class="container-fluid" style="background-color: #e9ecef5e;padding-bottom: 15px">
        <img src="{% static 'background.gif' %}" style="float: left;" width="350" height="270">
      <form class="loginform" method="post" action="/login/">
          {% csrf_token %}
          <div class="form-group">
              <label for="username">Username:</label>
              {{ form.username }}
           </div>
          <div class="form-group">
              <label for="pwd">Password:</label>
              {{ form.password }}
          </div>
          <div class="form-group form-check">
              <label class="form-check-label">
                <input class="form-check-input" type="checkbox" name="remember"> Remember me
              </label>
          </div>
            <button type="submit" class="btn btn-info">Submit</button>
          <button type="button" class="btn btn-info"><a href="{% url 'password_reset' %}">forgot password</a></button>
       </form>
  </div>
  {% endblock container %}
  {% block footer %}
  <div class="container-fliud text-success" style="text-align: center;background-color: #e9ecef5e;margin-top: 0px">
    <hr style="margin-top: 0px">
    <h5 class="text-info">Follow me - is a host where you can share your knowledge to others who follows.</h5><br>
  </div>
  {% endblock %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.13.0/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.2/js/bootstrap.min.js"></script>
</body>
</html>

templates/loggedin.html
{% extends 'home.html' %}
{% load static %}
{% block extra-css %}
  <link rel="stylesheet" href="{% static 'timeline.css' %}">
{% endblock %}
{% block header %}
{% endblock %}
{% block navbar %}
  <nav class="navbar navbar-expand-sm bg-light navbar-light">
    <ul class="nav  nav-white" id="log">
      <li class="nav-item active px-0">
        <a class="nav-link" href="{% url 'loggedin' %}"><i class="fa fa-home" style="color:lightslategrey;font-size:30px"></i></a>
      </li>
      <li class="nav-item px-0">
        <a class="nav-link" href="{% url 'followers' pk=user.pk %}"><i class="fa fa-group" style="color:lightslategrey;font-size:30px"></i></a>
      </li>
      <li class="nav-item px-0">
        <a class="nav-link" href="{% url 'profile' pk=user.pk %}"><i class="fa fa-user" style="color:lightslategrey;font-size:30px"></i></a>
      </li>
      <li class="nav-item px-0">
        <a class="nav-link" href="{% url 'friends' %}"><i class="fa fa-user-plus" style="color:lightslategrey;font-size:30px"></i></a>
      </li>
      <li class="nav-item px-0">
        <a class="nav-link" href="{% url 'logout' %}"><i class="fa fa-sign-out" style="color:lightslategrey;font-size:30px"></i></a>
      </li>
    </ul>
  </nav>
{% endblock %}
{% block container %}
    <div class="container" style="background-color: #f8f9fa">
    <form method="post" action="/post/">
        {% csrf_token %}
       <div class="form-group">
         <label for="write your post"><h4 class="text-info">Write your post : </h4></label>
         {{ form.text }}
       </div>
     <button type="submit" class="btn btn-primary">Post</button>
    </form>
    <hr>
  {% for post in posts %}
    <div class="layout">
    <div class="user">
       <img style="border-radius: 50%;" src="{{ post.username.user_details.image.url }}" alt="not uploaded" width="50px" height="50px">
    </div>
    <div class="content">
       <p>by <strong><span style="color: blue;"><a href="{% url 'profile' pk=post.username.pk %}">{{ post.username }}</a></span> </strong> at <strong>{{ post.published_date }}</strong></p>
       <p class="text-success">{{ post.text }}</p>

        <table class="tabl" width="100%">
           <tr>
               {% if post.id in likes %}
                  <td><a href="{% url 'delete_like' pk=post.pk %}"><i class="fa fa-thumbs-down" style="font-size:20px;color:blue"></i> unlike :({{ post.likes_set.count}})</a></td>
               {% else %}
                   <td><a href="{% url 'add_like' pk=post.pk %}"><i class="fa fa-thumbs-up" style="font-size:20px;color:blue"></i> Like :({{ post.likes_set.count}})</a></td>
               {% endif %}
               <td><a href="{% url 'post_details' pk=post.pk %}"><i class="fa fa-comment" style="font-size:20px;color:blue"></i> Comments:({{post.comments_set.count}})</td>
           </tr>
       </table>
      </div>
    <hr>
  </div>
  {% endfor %}
     {% with posts as items %}
            {% if items.has_other_pages %}

                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        {% if items.has_previous %}
                            <li class="page-item"><a class="page-link" href="?page={{ items.previous_page_number }}">&laquo; prev</a></li>
                        {% else %}
                            <li class="page-item disabled"><a class="page-link" href="#"><span>&laquo; prev</span></a></li>
                        {% endif %}

                        {% if items.has_next %}
                            <li class="page-item"><a class="page-link" href="?page={{ items.next_page_number }}">next &raquo;</a></li>
                        {% else %}
                            <li class="page-item disabled"><a class="page-link" href="#"><span>next &raquo;</span></a></li>
                        {% endif %}
                    </ul>
                </nav>

            {% endif %}
        {% endwith %}
    </div>
{% endblock %}

templates/login.html
{% extends 'home.html' %}
{% block header %}
{% endblock %}
{% block container %}
  <div class="container">
      <form class="loginform" method="post" action="/login/">
          {% csrf_token %}
          <div class="form-group">
              <label for="username">Username:</label>
              {{ form.username }}
           </div>
          <div class="form-group">
              <label for="pwd">Password:</label>
              {{ form.password }}
          </div>
          <div class="form-group form-check">
              <label class="form-check-label">
                <input class="form-check-input" type="checkbox" name="remember"> Remember me
              </label>
          </div>
            <button type="submit" class="btn btn-info">Submit</button>
            <button type="button" class="btn btn-info">forgot password</button>
       </form>
  </div>
{% endblock container %}

templates/my_posts.html
{% extends 'loggedin.html' %}
{% block container %}
<div class="container" style="background-color: #f8f9fa">
  <h4 style="color:blue;"><strong>my posts :</strong></h4><hr>
  {% for post in posts %}
    <div class="layout">
    <div class="content">
       <p> at <strong>{{ post.published_date }}</strong></p>
       <p class="text-success">{{ post.text }}</p>
        <table class="tabl" width="100%">
           <tr>
               <td><a href="{% url 'post_details' pk=post.pk %}"><i class="fa fa-comment" style="font-size:20px;color:blue"></i> Comments:({{post.comments_set.count}})</td>
               <td><a href="{% url 'delete_post' pk=post.pk %}"><i class="fa fa-trash-o" style="font-size:20px;color:blue"></i> delete post</a></td>
           </tr>
       </table>
      </div>
    <hr>
  </div>
  {% endfor %}
{% endblock %}

templates/post_details.html
{% extends 'loggedin.html' %}
{% block container %}
    {% load static %}
<div class="layout" style="margin: 0% 2%;">
    <h5 style="color: #00cc66;padding:5px 0px 0px 5px;">Post details :</h5><hr>
    <div class="user">
       <img style="border-radius: 50%;" src="{% static 'user-128.png' %}" width="50px" height="50px">
    </div>
    <div class="content">
       <p>by <strong><span style="color: blue;">{{ post.username }}</span> </strong> at <strong>{{ post.published_date }}</strong></p>
       <p>{{ post.text }}</p>
      </div><hr style="margin-top: 0px;margin-bottom: 0px;">
   <h5 style="color: #00cc66;padding: 3px 0px 0px 5px;">Comments :</h5><hr style="margin-top: 0px;margin-bottom: 0px;">
    <div style="padding: 0px 4px 0px 5px;">
    {% for comment in post.comments_set.all %}
        <p>{{ comment.text }}</p>
        <p>by <strong style="color: blue;">{{ comment.author }}</strong> at <strong>{{ comment.created_date }}</strong></p>
        <hr style="margin-top: 0px;margin-bottom: 0px;">
    {% endfor %}
    </div>
  <form action="{% url 'add_comment_to_post' pk=post.pk %}" method="post">
      {% csrf_token %}
      {{ form.text }}
      <button style="margin: 5px 0px 5px 5px;" type="submit" class="btn btn-primary">Add-comment</button>
  </form>
</div>
{% endblock %}

templates/signup.html
{% extends 'home.html' %}
{% block header %}
{% endblock %}
{% block container %}
    {% load bootstrap %}
  <div class="container">
      <form class="loginform" method="post" action="/signup/">
          {% csrf_token %}
          {{ form|bootstrap }}
          <button type="submit" class="btn btn-info">Sign-up</button>
       </form>
  </div>
{% endblock %}